import React, { useEffect, useRef, useState } from 'react';
import { Heart, Pause, Play, Sparkles, Volume2, VolumeX, Wind } from 'lucide-react';
import { ResonanceCanvas } from '../components/ResonanceCanvas';
import { TraceRelax } from '../components/TraceRelax';

const melody = [261.63, 329.63, 392, 523.25, 392, 329.63, 293.66, 349.23, 440, 523.25, 440, 349.23];

export const EmpathyLounge = ({ user, socketHook }) => {
  const [pulseSent, setPulseSent] = useState(false);
  const [selectedColor, setSelectedColor] = useState('#2dd4bf');
  const [musicPlaying, setMusicPlaying] = useState(false);
  const [muted, setMuted] = useState(false);
  const [reduceMotion, setReduceMotion] = useState(false);
  const [breathing, setBreathing] = useState(false);
  const [breathSeconds, setBreathSeconds] = useState(4);
  const [trackProgress, setTrackProgress] = useState(0);
  const audioRef = useRef(null);
  const melodyTimerRef = useRef(null);

  useEffect(() => { if (socketHook?.emitLoungeJoin && user) socketHook.emitLoungeJoin({ alias: user.alias, avatarSeed: user.avatarSeed }); }, [socketHook, user]);
  useEffect(() => () => { window.clearInterval(melodyTimerRef.current); audioRef.current?.gain?.gain.setTargetAtTime(0, audioRef.current.context.currentTime, .25); }, []);
  useEffect(() => { if (audioRef.current) audioRef.current.gain.gain.value = muted ? 0 : breathing ? .018 : .045; }, [muted, breathing]);
  useEffect(() => { if (!breathing) return undefined; const timer = window.setInterval(() => setBreathSeconds((value) => value > 1 ? value - 1 : 4), 1000); return () => window.clearInterval(timer); }, [breathing]);
  useEffect(() => { if (!musicPlaying) return undefined; const timer = window.setInterval(() => setTrackProgress((value) => (value + 1) % 100), 2800); return () => window.clearInterval(timer); }, [musicPlaying]);

  const playMelody = () => {
    const AudioContext = window.AudioContext || window.webkitAudioContext;
    if (!AudioContext) return;
    const context = audioRef.current?.context || new AudioContext(); const gain = context.createGain(); gain.gain.value = muted ? 0 : .045; gain.connect(context.destination); audioRef.current = { context, gain };
    let note = 0;
    const schedule = () => { const oscillator = context.createOscillator(); const noteGain = context.createGain(); oscillator.type = 'sine'; oscillator.frequency.value = melody[note % melody.length]; noteGain.gain.setValueAtTime(.001, context.currentTime); noteGain.gain.exponentialRampToValueAtTime(.22, context.currentTime + .08); noteGain.gain.exponentialRampToValueAtTime(.001, context.currentTime + 1.35); oscillator.connect(noteGain).connect(gain); oscillator.start(); oscillator.stop(context.currentTime + 1.4); note += 1; };
    if (context.state === 'suspended') context.resume(); schedule(); melodyTimerRef.current = window.setInterval(schedule, 1400); setMusicPlaying(true);
  };
  const stopMelody = () => { window.clearInterval(melodyTimerRef.current); audioRef.current?.gain?.gain.setTargetAtTime(0, audioRef.current.context.currentTime, .25); setMusicPlaying(false); };
  const handleSendCommunalPulse = () => { socketHook?.emitResonancePulse?.({ phase: 'calm', intensity: 1.5, color: selectedColor }); setPulseSent(true); window.setTimeout(() => setPulseSent(false), 2000); };

  return <div className={`max-w-6xl mx-auto px-4 py-8 space-y-8 ${reduceMotion ? 'reduce-motion' : ''}`}>
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 glass-panel p-6 rounded-3xl border border-brand-500/20"><div><div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-brand-500/10 text-brand-700 text-xs font-semibold mb-2 border border-brand-500/20"><Sparkles className="w-4 h-4 text-calm-cyan" /><span>Listen · Breathe · Create</span></div><h1 className="text-2xl sm:text-3xl font-extrabold font-display text-slate-900">Communal Empathy Lounge</h1><p className="text-xs sm:text-sm text-slate-600 mt-1 max-w-xl">A peaceful corner to listen, breathe, trace, and keep a small happy moment.</p></div><div className="flex items-center space-x-3 bg-white/90 px-5 py-3 rounded-2xl border border-slate-200 shadow-sm shrink-0"><span className="w-3 h-3 rounded-full bg-emerald-500 animate-ping" /><div><span className="text-[10px] text-slate-500 uppercase tracking-wider block">Students in resonance</span><span className="text-xl font-black font-display text-emerald-600">{socketHook?.loungeCount || 38} Connected</span></div></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1.35fr)_minmax(280px,.65fr)] gap-6"><div className="space-y-4">
      <div className="glass-panel-glow rounded-[2rem] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="space-eyebrow mb-2">Listen first</p><h2 className="text-2xl font-black text-sky-950">Peaceful Moment <span aria-hidden="true">🎵</span></h2><p className="text-sm text-slate-600 mt-1">Take a breath and enjoy the music.</p></div><div className={`music-orbit ${musicPlaying ? 'music-playing' : ''}`}><span>✦</span></div></div><div className="mt-5 flex items-center gap-3"><span className="text-xs text-slate-500">0:00</span><div className="h-2 flex-1 rounded-full bg-sky-100 overflow-hidden"><div className="h-full bg-gradient-to-r from-cyan-300 to-pink-300 rounded-full" style={{ width: `${trackProgress}%` }} /></div><span className="text-xs text-slate-500">4:05</span></div><div className="mt-5 flex flex-wrap items-center gap-3"><button onClick={musicPlaying ? stopMelody : playMelody} className="flex items-center gap-2 rounded-xl bg-sky-600 text-white px-4 py-2.5 text-sm font-bold shadow-lg shadow-sky-200">{musicPlaying ? <Pause size={16} /> : <Play size={16} fill="currentColor" />}{musicPlaying ? 'Pause' : 'Play'}</button><button onClick={() => setMuted((value) => !value)} className="p-2.5 rounded-xl border border-sky-200 bg-white/80 text-sky-800" title={muted ? 'Sound off' : 'Sound on'}>{muted ? <VolumeX size={17} /> : <Volume2 size={17} />}</button><div className="music-waves ml-auto" aria-label="Soft music visualizer"><i /><i /><i /><i /><i /></div></div></div>
      <div className="glass-panel rounded-[2rem] p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="space-eyebrow mb-2">Listen + breathe</p><h2 className="text-xl font-black text-sky-950">A softer rhythm <Wind className="inline text-cyan-500" size={19} /></h2></div><button onClick={() => { setBreathing((value) => !value); if (!musicPlaying) playMelody(); }} className="rounded-xl bg-white border border-sky-200 px-3 py-2 text-xs font-bold text-sky-800">{breathing ? 'Pause' : 'Start'}</button></div><div className="flex items-center gap-5 mt-4"><div className={`breath-orb ${breathing ? 'breath-orb-active' : ''}`}><span>{breathing ? breathSeconds : '4'}</span></div><p className="text-sm text-slate-600 max-w-sm">{breathing ? 'Breathe in slowly, then let your breath go.' : 'When you are ready, follow the gentle circle.'}</p></div></div>
      <TraceRelax musicPlaying={musicPlaying} onStartMusic={playMelody} muted={muted} reduceMotion={reduceMotion} />
      <div className="h-[280px] sm:h-[320px]"><ResonanceCanvas socketHook={socketHook} moodColor={selectedColor} activeCount={socketHook?.loungeCount || 38} /></div>
      <div className="glass-panel p-4 rounded-2xl border border-slate-200 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center space-x-2"><span className="text-xs text-slate-700 font-semibold">Particle aura:</span><div className="flex items-center space-x-1.5">{['#2dd4bf', '#38bdf8', '#818cf8', '#34d399', '#fb7185'].map((color) => <button key={color} onClick={() => setSelectedColor(color)} style={{ backgroundColor: color }} className={`w-6 h-6 rounded-full transition-all ${selectedColor === color ? 'ring-2 ring-slate-800 scale-110' : 'opacity-70 hover:opacity-100'}`} title="Choose aura color" />)}</div></div><button onClick={handleSendCommunalPulse} className="flex items-center space-x-2 px-4 py-2 rounded-xl bg-gradient-to-r from-brand-500 to-calm-cyan text-white font-bold text-xs shadow-md"><Sparkles className="w-3.5 h-3.5" /><span>{pulseSent ? 'Pulse Sent! ✨' : 'Send Calm Wave to Room'}</span></button></div>
    </div><div className="space-y-4"><div className="glass-panel-glow p-5 rounded-3xl border border-brand-500/20"><div className="flex items-center justify-between"><div><p className="space-eyebrow">Comfort controls</p><h3 className="font-black text-sky-950 mt-1">Make it yours</h3></div><button onClick={() => setReduceMotion((value) => !value)} className={`text-xs px-3 py-2 rounded-xl border ${reduceMotion ? 'bg-sky-100 border-sky-300 text-sky-800' : 'bg-white border-sky-200 text-slate-600'}`}>{reduceMotion ? 'Motion off' : 'Reduce animations'}</button></div><div className="mt-5 space-y-3 text-sm"><label className="flex items-center justify-between gap-3"><span className="flex items-center gap-2"><VolumeX size={16} className="text-cyan-500" /> Mute music</span><input type="checkbox" checked={muted} onChange={(event) => setMuted(event.target.checked)} className="accent-sky-500" /></label><label className="flex items-center justify-between gap-3"><span className="flex items-center gap-2"><Volume2 size={16} className="text-cyan-500" /> Sound on/off</span><input type="checkbox" checked={!muted} onChange={(event) => setMuted(!event.target.checked)} className="accent-sky-500" /></label></div></div><div className="p-5 rounded-3xl glass-panel border border-slate-200 text-xs text-slate-600 space-y-2"><div className="flex items-center space-x-2 text-slate-800 font-semibold"><Heart className="w-4 h-4 text-rose-500" /><span>Campus co-regulation</span></div><p className="leading-relaxed">Your calm wave joins the room softly. No talking or performing is needed here.</p></div></div></div>
  </div>;
};